on: [push, pull_request]

name: Run tests

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:devel
    steps:
    - uses: actions/checkout@v2

    - name: Get latest CMake
      uses: lukka/get-cmake@latest

    - name: Configure the build 
      run: cmake -S . -B build 

    - name: Set directories
      run: |
        echo "R_PKG_DIR=${R_HOME}/site-library" >> $GITHUB_ENV

    - name: Restore the package directory
      uses: actions/cache@v2
      with:
        path: ${{ env.R_PKG_DIR }}
        key: preinstalled-packages

    - name: Install dependencies
      shell: Rscript {0}
      run: |
        BiocManager::install(c("DelayedArray", "Rcpp", "testthat"))

    - name: Install the test package
      run: R CMD INSTALL tests

    - name: Run the tests
      shell: Rscript {0}
      run: |
        setwd("tests/tests")
        testthat::test_file("testthat.R", stop_on_failure=TRUE)

